linters:
  enable:
    - gas
    - golint
    - interfacer
    - unconvert
    - goconst
    - goimports
    - bodyclose
    - prealloc
    - scopelint
    - maligned
    - dupl
    - gocyclo
    - unparam
    - depguard
    - gocritic
