linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - bodyclose
    - govet
    - gosec

    - staticcheck
    - typecheck
    - gosimple
    - prealloc
    - nolintlint

    - stylecheck
    - gocritic
    - revive
    - gofmt
    - goimports
    - lll
    - nlreturn

    - dogsled
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - goprintffuncname
    - misspell
    - nakedret
    - rowserrcheck
    - unconvert
    - unparam
    - unused

  # TODO:
  # - noctx
  # - depguard
  # - dupl # skip in tests?

  # disabled:
  # - asciicheck
  # - gochecknoglobals
  # - godot
  # - godox
  # - goerr113
  # - nestif
  # - testpackage
  # - wsl
  # - whitespace

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/vtopc/epoch
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
      # - ifElseChain # ERRO Invalid gocritic settings: gocritic [enabled]tag "ifElseChain" doesn't exist
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - octalLiteral
      - wrapperFunc
      - whyNoLint
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/vtopc/epoch
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
    #settings:
    #  printf:
    #    funcs:
    #      - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
    #      - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
    #      - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
    #      - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 50
